### ISSUE TITLE
SegFault

### ISSUE THREAD

**Issue by choubacha** [henrik/vim-yaml-flattener#7]
Not sure how this happened, but after installing with Vundle:

![image](https://user-images.githubusercontent.com/2043529/46564853-c8065600-c8be-11e8-9ab6-9725bd731f83.png)

Here's my vim version info:

![image](https://user-images.githubusercontent.com/2043529/46564866-d94f6280-c8be-11e8-919d-a006c5388bb8.png)

**Comment by henrik** [comment]
Hi @kbacha! So sorry for the delay. Could it be this issue? https://github.com/Homebrew/legacy-homebrew/issues/23938#issuecomment-31549058

**Comment by choubacha** [comment]
@henrik Could be, I'll investigate.
